### ISSUE TITLE
소통공간 오류 수정

### ISSUE THREAD

**Issue by akrudal** [telling-me/tellingme-iOS#101]
### 📃 Description
소통공간 뷰 수정합니다.
Compositional CollectionView로 했더니 전체 로딩 걸리는 문제가 있어서 각 뷰들을 분리하겠습니다.
좋아요 기능, 정렬 기능에 오류가 생기는 부분도 수정하겠습니다.

### ✔ Todo
- [ ] Compositional CollectionView -> View+ CollectionView로 바꾸기
- [ ] 좋아요 기능 리팩토링
- [ ] 정렬 기능 리팩토링

### 🔴 ETC
예상 개발 기간: 12시간
