### ISSUE TITLE
[fix] :  회원가입 후 푸시알림에 생기는 문제를 수정합니다.

### ISSUE THREAD

**Issue by akrudal** [telling-me/tellingme-iOS#117]
### 📃 Description
회원가입 후에 홈에 오면 생기는 알림 동의 모달창에 관한 오류사항입니다.
1. 저희 쪽에서는 푸시 notification status와 push token을 서버로 request하는 로그가 찍힙니다.
2. response오는 로그도 찍힙니다.
3. 디비에는 저장이 되지 않습니다.
4. 서버쪽에 push token만 api 기록이 남아있습니다.
따라서 서버팀과 합의 후 status와 token을 한꺼번에 보내는 api를 새로 구현하기로 하였습니다.

이 기능은 3차 때 뺄 예정입니다!

### ✔ Todo
- [x] pushnotification api 추가하기
- [x] 회원가입 이후 pushnotification logic 수정하기
- [x] 이미 데이터가 잘 못 들어간 사람들에게 알림창 띄우기 ( 홈에서 getAPI하도록 하겠습니다 )

### 🔴 ETC
기타 사항을 적어주세요.
예상 개발 기간: 4시간
