### ISSUE TITLE
2.5차 배포 전에 오류사항을 수정합니다.

### ISSUE THREAD

**Issue by akrudal** [telling-me/tellingme-iOS#121]
### 📃 Description
2.5차 배포 전에 오류 사항을 수정합니다.

### ✔ Todo
- [x] 홈 탭바 첫번째로 위치시키기
- [x] 고민 고를 때 정렬 + 띄어쓰기 없이 배열에 들어가게하기
- [x] 스크롤 시에 answer 없다는 오류 수정하기
- [x] 나의 서재 index 수정하기
- [x] 서재 layout 바꾸기
- [x] 감정 문구 수정하기

### 🔴 ETC
기타 사항을 적어주세요.
예상 개발 기간: 4시간
