### ISSUE TITLE
[fix]: 홈화면에서의 알림창 UI 버그와 텝바 색상에 대한 UI 버그를 고칩니다.

### ISSUE THREAD

**Issue by PecanPiePOS** [telling-me/tellingme-iOS#126]
### 📃 Description
1. 알림창에서 "전체읽기" 를 누르고 홈화면으로 나갔을때 데이터가 최신화되지 않는 것을 고칩니다.
2. 텝바의 색상이 깨지는 것을 방지합니다.
-> 테플로 올려서 기존의 버그가 발생하던 ui 를 가진 사람과 테스트 해야합니다.
3. 바뀐 알림창 DB 구조를 채택합니다.
4. 백그라운드에서 돌아왔을 때 업데이트 됩니다. (애니메이션은 지금 안됩니다.)

### ✔ Todo
- [ ] 알림 읽기
- [ ] 텝바  색상 방지하기
- [ ] 바뀐 알림창 DB 구조를 채택합니다.
- [ ] 백그라운드에서 돌아왔을 때 업데이트 됩니다. (애니메이션은 지금 안됩니다.)

### 🔴 ETC
기타 사항을 적어주세요.
예상 개발 기간: 5
