### ISSUE TITLE
[fix]: 2.5차 오류사항을 수정합니다 _ 2차

### ISSUE THREAD

**Issue by akrudal** [telling-me/tellingme-iOS#129]
### ✔ Todo
- [x] 고민 배열 - 띄어쓰기 없게 순서대로 보내기 (설정에서 재확인)
- [x] 나의서재 <?> 스윽 올라오는 모션 넣기
- [x] 나의 서재 사이즈 비율로 조정하기

### 🔴 ETC
기타 사항을 적어주세요.
예상 개발 기간: 6시간
