### ISSUE TITLE
[style] : 회원가입시 유저 정보 받기

### ISSUE THREAD

**Issue by akrudal** [telling-me/tellingme-iOS#14]
### 📃 Description
- progressbar는 gradient로 라이브러리 설치하여 이용
- progressbar 값은 0부터 시작x, 0.x로 시작
- mbti pickerview custom하기
- 생일은 오늘보다 넘어가지 않고, 1999년 1월 1일로 시작
- 닉네임 제한 있음 (한글만 가능. 숫자 특수기호 영문 안됨. 욕설 안됨)

### ✔ Todo
- [ ] signupviewcontroller + storyboard
- [ ] progress bar
- [ ] pageviewcontroller
- [ ] 서비스 이용 약관 viewcontroller + storyboard
- [ ] 닉네임 storyboard + viewcontroller
- [ ] 성별 storyboard + 성별 viewcontroller
- [ ] 생일 storyboard + 생일 viewcontroller 
- [ ] 고민 storybaord + viewcontroller
- [ ] 직업 storyboard + viewcontroller
- [ ] mbti storyboard + viewcontroller

### 🔴 ETC
기타 사항을 적어주세요.
예상 개발 기간: 30시간
