### ISSUE TITLE
QA 오류 사항을 반영합니다.

### ISSUE THREAD

**Issue by akrudal** [telling-me/tellingme-iOS#147]
### 📃 Description
1.1.1 버전에 수정할 사항은 다음과 같습니다.

### ✔ Todo
- [ ] 현재 카드뷰 7줄로 된 것 -> 가득 차게 늘리기
- [ ] 보조문구 줄간격&컬러 수정
- [ ] 그림자 안 들어가있는 부분 해결 (모션은 보류함)
- [ ] 회원탈퇴, 로그아웃 시에도 온보딩로그인화면 반영하기
- [ ] 답변 수 5개로 변경 
- [ ] 정렬 토글 변경했을 때 인덱스 새로고침 되지 않고 유지되어버림
- [ ] 리스트를 맨 밑으로 내려서 마지막 답변에 들어갔다가 뒤로 다시 나오면 생기는 오류
- [ ] 애플 자동로그인 안되는 오류 수정하기

### 🔴 ETC
기타 사항을 적어주세요.
예상 개발 기간: 8시간
