### ISSUE TITLE
[fix]:질문 피드백 뷰 에러를 수정합니다.

### ISSUE THREAD

**Issue by akrudal** [telling-me/tellingme-iOS#163]
### 📃 Description
issue에 대한 상세 내용을 적어주세요.

### ✔ Todo
- [ ] 그렇다/그렇지 않다 위치 바꾸기
- [ ] 제출하기 중복 막기
- [ ] 제출하기 이후 화면 전환 이벤트 적용하기

### 🔴 ETC
기타 사항을 적어주세요.
예상 개발 기간: 8시간
