### ISSUE TITLE
[feat] : 유저 정보 받기 기능 구현

### ISSUE THREAD

**Issue by akrudal** [telling-me/tellingme-iOS#20]
### 📃 Description
이전에 미처 하지 못 한 부분을 더 하며 기능 구현
- 닉네임 화면 => 닉네임 중복시 error 화면은 서버 api 통신하며 붙이도록 함
- 생일 화면 => 년도, 월, 일 순으로 선택할 수 있어야함
- 

### ✔ Todo
- [ ] 화면 순서 정리
- [ ] 프로그레스 바 기능 수정
- [ ] 전체 약관 동의 화면 => checkmark 색상, check 해야 페이지 이동
- [ ] 닉네임 화면 => 토스트창, 2글자 이상 제한
- [ ] 성별 화면 => 컴포넌트 뷰 이용하기
- [ ] 직업 화면 => 컴포넌트화 하기
- [ ] 고민 화면 => 아이콘 넣기
- [ ] 생일 화면,mbti 화면 => 컴포넌트 이용하기

### 🔴 ETC
기타 사항을 적어주세요.
예상 개발 기간: 20시간
