### ISSUE TITLE
[feat] : 로그인 화면 만들기

### ISSUE THREAD

**Issue by akrudal** [telling-me/tellingme-iOS#25]
### 📃 Description
모든 도형은 코드 구현이 svg로 사용하도록 한다.
이유는
1. 도형들이 figma vector로 이루어져있기 때문에 path에 대한 정보가 하나도 나오지 않는다.
2. 그냥 원, 삼각형이 아니라 둥근 모서리가 포함되어 있다.
3. 단색이 아니라 그라데이션 칼러가 들어가야 한다.

이를 코드로 구현하려면 너무 많은 시간과 노력이 필요하기 때문에, svg로 사용한다.

### ✔ Todo
- [ ] 카카오로그인 버튼 만들기
- [ ] 애플 로그인 버튼 만들기
- [ ] 바텀시트 만들기
- [ ] 도형 svg를 사용하여 레이아웃 잡기
- [ ] 도형 애니메이션 주기

### 🔴 ETC
기타 사항을 적어주세요.
예상 개발 기간: 10시간
