### ISSUE TITLE
[feat] 회원가입 수정사항

### ISSUE THREAD

**Issue by akrudal** [telling-me/tellingme-iOS#27]
### ✔ Todo
- [ ] 생일 request 오류 고치기
- [ ] 닉네임 욕설 검사하기
- [ ] 닉네임 유효성 검사 api 추가하기
- [ ] 닉네임 유효성 검사 실패시 warning view 추가하기

### 🔴 ETC
기타 사항을 적어주세요.
예상 개발 기간: 8 시간
