### ISSUE TITLE
[feat] : 소셜로그인 및 회원가입 1차 피드백

### ISSUE THREAD

**Issue by akrudal** [telling-me/tellingme-iOS#30]
### 📃 Description
소셜로그인 및 회원가입 페이지들 1차 피드백 받기
나중에 리팩토링할거 줄이기 위해서 코드 바뀌는 viewcontroller들은 viewmodel을 구현하기

### ✔ Todo
- [ ] 건너뛰기 버튼 만들기
- [ ] secondary icon button 컴포넌트화
- [ ] nextButton disable 구현하기
- [ ] 알림 허용 페이지 만들기
- [ ] 카카오앱으로 로그인하기 구현
- [ ] 카카오 동의항목 구현
- [ ] 닉네임 유효검사 api 추가하기
- [ ] 직업 '기타(5)' 선택 시 유효성 검사 API 추가하기

### 🔴 ETC
기타 사항을 적어주세요.
예상 개발 기간: 16시간
