### ISSUE TITLE
[style] : 홈 화면

### ISSUE THREAD

**Issue by akrudal** [telling-me/tellingme-iOS#34]
### 📃 Description
홈 화면 구현
* navigationbar 컴포넌트화 예정

### ✔ Todo
- [ ] custom tab bar 만들기
- [ ] custom header 만들기
- [ ] 그림자 적용하기
- [ ] home 화면 레이아웃 잡기
- [ ] 애니메이션 요소 적용하기
- [ ] 헤더 컴포넌트화하여 navigationbar로 사용하기
- [ ] 로그인 분기 처리하여 home화면을 rootviewcontroller로 설정하기

### 🔴 ETC
기타 사항을 적어주세요.
예상 개발 기간: 20시간
