### ISSUE TITLE
[fix] : 1차 피드백 수정 사항

### ISSUE THREAD

**Issue by akrudal** [telling-me/tellingme-iOS#39]
### ✔ Todo
- [ ] 애플 로그인
- [ ] 회원가입 후 바로 로그인 넘어가기
- [ ] 직업 이미지 넣기
- [ ] 직업 배경 사진
- [ ] 움직이는 view들 그림자 넣기
- [ ] 애플 로고, 카카오 로고 수정하기
- [ ] 전문보기 글씨체 변경
- [ ] 닉네임 8글자 제한

### 🔴 ETC
기타 사항을 적어주세요.
예상 개발 기간:
