### ISSUE TITLE
[style]: setting 화면

### ISSUE THREAD

**Issue by akrudal** [telling-me/tellingme-iOS#45]
### 📃 Description
dropdowntableviewcell만 있었는데 너무 공통된 부분도 많아서 dropdowntableviewcontroller를 만들기로 함. 
이제 viewcontroller에서 dropdwontableviewcontroller를 상속하면 delegate와 datasource 함수들을 또 정의해주지 않아도 된다.

또한 나의 정보 수정하기가 하나의 viewcontroller로 이루어져 있으면  하나의 viewcontroller에 5개정도가 되는 collectionview나 tableview가 필요하다. => containerview로 viewcontroller를 감싸서 개별적으로 관리하도록 한다.

### ✔ Todo
- [ ] setting header view
- [ ] setting main view
- [ ] 내 정보 수정하기 레이아웃
- [ ] 공통 dropdwonviewcontroller 만들기
- [ ] mbti tableview refactoring (재사용 뷰 만들기)
- [ ] birthday tableview refactoring (재사용 뷰 만들기)
- [ ] Chips collectionViewCell 만들
- [ ] Chips collectionViewcontroller 만들기 (재사용 뷰 만들기)

### 🔴 ETC
기타 사항을 적어주세요.
예상 개발 기간: 18시간
