### ISSUE TITLE
[feat] : answer 로직 추가

### ISSUE THREAD

**Issue by akrudal** [telling-me/tellingme-iOS#51]
### 📃 Description
answer 전체 과정을 수정한다.
현재는 answer 화면만 있었는데, 등록, 업데이트, 삭제 등의 과정을 모두 추가한다.

각 action들이 모두 비슷한 코드를 가지고 있어서 추후에 ansewrviewcontroller를 상속 리팩토링 할 예정이다.

또한 수정 삭제 메뉴처럼 Pulldown menubar를 dropdown 코드와 비슷하게 작성하여 추가한다.
ios14버전 이상부터 pulldown을 이용할 수 있다. (우리는 iOS13)

### ✔ Todo
- [ ] modifyanswerviewcontroller 추가
- [ ] answercompletedviewcontroller 추가
- [ ] updateanswer api 추가
- [ ] deleteanswer api 추가
- [ ] postanswer api 추가
- [ ] getanswerapi 추가
- [ ] pulldown custom 추가

### 🔴 ETC
기타 사항을 적어주세요.
예상 개발 기간: 4시간
