### ISSUE TITLE
[feat] : settingAPI 추가

### ISSUE THREAD

**Issue by akrudal** [telling-me/tellingme-iOS#62]
### 📃 Description
설정 페이지 UI와 기능 모두 추가한다.

### ✔ Todo
- [ ] 회원정보 반환 API
- [ ] 로그아웃 API
- [ ] 알림 상태 반환 API
- [ ] 회원정보 수정 API
- [ ] 알림 상태 변경 API
- [ ] 회원 탈퇴 API
- [ ] 회원 탈퇴 UI
- [ ] 개인정보처리방침 UI

### 🔴 ETC
기타 사항을 적어주세요.
예상 개발 기간: 8시간
