### ISSUE TITLE
[feedback] : 1차 피드백 수정 사항

### ISSUE THREAD

**Issue by akrudal** [telling-me/tellingme-iOS#67]
### 📃 Description
- 로그인 화면 서버 에러가 밀리초 단위로 들어오기 때문에 자동로그인 우선 후작업으로 미루기
아직 에러가 왜 나는진 모르겠지만 생각해봤을 때 웹에서 로그인하고 앱에서 저장된 토큰으로 들어가게 되면 당연히 다른 토큰이기 때문에 유효하지 않아 오류가 날 수 밖에없음. => 따로 이슈사항으로 작업하기

- 답변 작성 시에 성공 문구는 없긴 한데, 적혀있어서 논의사항으로 적기
- 한글은 5글자인데 6/500 으로 뜨기도 함, 글자 수 세기 알고리즘 바꿀 수 있을지 확인해보기

- 4글자 이하 적었을 때 문구 뭐라하지?ㅜ

### ✔ Todo
- [ ] 감정 선택이 구분이 안됨
- [x] 답변 입력창 500>300자로 수정 (프리미엄이 500, 기본은 300자)
- [x] 답변 리스트에 13월의 존재
- [x] 답변 최소 길이 제한 (4글자까지) 
- [x] ’푸쉬’ > ‘푸시’ 문구 수정, 선택 토글 넣기
- [x] 닉네임` 변경 안됨
- [ ]  고민 수정할 때 2가지를 한 번씩 골라야 선택 인정이 됨
- [x]  기타 ’직접 입력’에 안적었는데도 수정 완료됨
- [ ] 직접 입력’선택 안되어있을 때, 문구 ‘기타 선택 후 …’ > ‘직접 입력’ 으로 문구 수정
- [x] 성별 남성/여성 선택이 안됨
- [x] 회원 탈퇴 들어가면 이미 체크박스
- [x] 회원 탈퇴 에서 ‘탈퇴하기’ 누르면 뜨는 모달에서 ‘저장하기’ > ‘탈퇴하기’ 로 수정

### 🔴 ETC
기타 사항을 적어주세요.
예상 개발 기간: 3시간
