### ISSUE TITLE
[feat]: Splash 화면 추가

### ISSUE THREAD

**Issue by akrudal** [telling-me/tellingme-iOS#73]
### 📃 Description
Splash 화면을 추가하여 로그인/ 홈 화면 분기처리 기능을 추가

### ✔ Todo
- [ ] mp4 파일받기
- [ ] mp4 파일 재생하기
- [ ] 첫 화면을 splash로 설정하기
- [ ] 로그인/홈화면 분기처리하기

### 🔴 ETC
기타 사항을 적어주세요.
예상 개발 기간:
