### ISSUE TITLE
[feedBack] : 테스트결함

### ISSUE THREAD

**Issue by akrudal** [telling-me/tellingme-iOS#75]
### 📃 Description
14일날 진행했던 테스트 결함을 수정한다.

### ✔ Todo
- [x] 직업 아이콘 채워넣기
- [x] 성별 아이콘 채워넣기
- [x] mbti 페이지 '완료' 문구가 아닌 '>(화살표)'로 수정
- [x] 버튼 윙펜 아이콘 채워넣기
- [x] 질문 볼드체로 변경
- [x] '답변 완료!' 볼드체로 변경
- [x] 4글자부터 허용되게 수정
- [x] 답변 수정화면에서 날짜 띄우기
- [x] 성별/생년월일 입력 후에는 disabled버튼 색상 처리
- [x] 6월 답변인데 다른 월 리스트에도 뜨는 문제
- [ ] 탈퇴 주의사항 넣어놓기
- [ ] 서비스 이용 약관 두 가지(이용약관/개인정보처리방침)로 분리
- [ ] 원 애니메이션 멈춤 문제 해결

### 🔴 ETC
기타 사항을 적어주세요.
예상 개발 기간: 2시간
