### ISSUE TITLE
[feedback] : 테스트 결함 2차

### ISSUE THREAD

**Issue by akrudal** [telling-me/tellingme-iOS#79]
### ✔ Todo
- [ ] 질문 받아오는 날짜 6시간 계산 안 되어있음
- [ ] 푸시알림 동의로 회원가입이 되지 않음
- [ ] 홈화면 애니메이션 멈추는거 수정
- [x] mbti 입력 페이지에서 우측 하단 버튼 이상!
- [x] 내 정보 변경에서 기타 직업으로 설정해놓으면 흐릿하게 보임
- [x] 답변 리스트 우상단에 설정버튼 누르면 설정으로 안감
- [x] 탈퇴 주의사항 넣어놓기
- [x] 푸시 알림 아이폰 설정 동의 alert 창 띄우기
- [x] 답변리스트 답변 없을 때 view 수정
- [x] 직업에 직장인 아이콘에서 윗쪽 채워지지 않아야 함
- [x] 탭 눌렀을 때 나오는 화면들 밑에 42px 패딩 있어야 함
- [x] 이용 약관 헤더 타이틀이 '설정'이라고 되어 있음 -> '이용 약관'으로 변경
- [x] 윙펜 누르고 들어가면 오른쪽 위 화살표가 아래를 향하고 있음
- [x] 내 정보 수정하기 '완료' 버튼 누르면 모달창이 안 나옴
- [ ] 내 정보 수정하기 mbti 선택 안 했을 때 기본 문구 없음
- [x] 내 정보 수정하기-닉네임 막히는게 없음 (특수기호, 영어, 글자수 등)
- [x] 서비스 이용 약관 두 가지(이용약관/개인정보처리방침)로 분리
- [x] 아이콘 -> 그림자 아이콘으로 교체

### 🔴 ETC
기타 사항을 적어주세요.
예상 개발 기간: 4시간
