### ISSUE TITLE
[feedback] : 테스트 결함 3차

### ISSUE THREAD

**Issue by akrudal** [telling-me/tellingme-iOS#81]
### 📃 Description
issue에 대한 상세 내용을 적어주세요.

- 논의사항1: 애플로그인 토큰으로 자동로그인을 하게 되면 만료된 토큰값인데도 계속 이용해야함.

### ✔ Todo
- [x] "오늘" 답변 수정화면에서 질문/문구/날짜 안뜨는 문제
- [x] 두글자 누르고 완료 누르면 줄바꿈이 됨 -> 키보드를 완료 대신 엔터키보드로 바꾸기 // 현재 키보드 액션이 아예 안먹음
- [x] "지난" 답변 수정화면에서 답변 아예 안보임(오늘 답변 수정 가능 / 지난 답변 수정 불가능)
- [x] 탈퇴 주의사항 넣어놓기
- [x] 내 정보 변경에서 기타 직업으로 설정해놓으면 완료버튼이 안눌림
- [x] 내 정보 수정하기 닉네임 욕설 막기
- [x] 내 정보 수정하기 유효성 검사 추가하기
- [x] 탈퇴 주의사항 텍스트 위에 '슬픈 듀이' 넣기
- [x] '회원 탈퇴' 탭 위에 'FAQ' 탭 추가 (링크 연결)
- [x] 생년월일 / mbti 드랍다운 화살표 안 바뀜
- [x] 애플 로그인 로직 수정하기 (토큰값과 소셜아이디값 혼동으로 인해 잘 못 함)
- [ ] 스플래쉬 mp4->gif로 바꾸기
- [x] mbti 중복 오류
- [x] 회원 탈퇴 이미지 추가
- [x] 답변 리스트 이미지 추가  
- [x] apple login 로직 바꾸기
- [x] 감정 로직 수정 => 서버쪽에서 감정 처리가 0부터가 아니라 1부터임

### 🔴 ETC
기타 사항을 적어주세요.
예상 개발 기간:
