### ISSUE TITLE
[feat] 소통공간 답변 & 신고 뷰 만들기

### ISSUE THREAD

**Issue by akrudal** [telling-me/tellingme-iOS#93]
### 📃 Description
소통 공간의 답변과/ 신고 뷰를 만든다.
답변같은 경우에 재사용 되는 뷰이기 때문에 코드로 다시 만든다.

### ✔ Todo
- [ ] 신고 api 연동하기
- [ ] 신고 view 만들기
- [ ] 신고 viewModel 만들기
- [ ] header 재사용 뷰 만들기
- [ ] emotion 재사용 뷰 만들기
- [ ] question 재사용 뷰 만들기
- [ ] textView 재사용 뷰 만들기
- [ ] 소통공간 답변 view 만들기
- [ ] 좋아요 api 연동하기

### 🔴 ETC
기타 사항을 적어주세요.
예상 개발 기간: 8시간
