### ISSUE TITLE
[feedback]: 수정사항 1

### ISSUE THREAD

**Issue by akrudal** [telling-me/tellingme-iOS#95]
### 📃 Description
전체적으로 수정사항을 한 번 적용한다.

### ✔ Todo
- [x] 앱 아이콘 바꾸기
- [x] 앱 이름 Tellingme -> 텔링미로 바꾸기
- [x] 회원가입 프로그레스바 바꾸기
- [x] 회원가입 출생년도 키보드 이슈 고치기
- [x] 이용약관, 개인정보처리방침 text 파일로 교체하기(스토리보드가 너무무거워짐)
- [x] 푸시알림 토큰 바뀐 경우 서버에게 토큰값 보내는 과정 추가하기
- [x] 설정에서 푸시알림 안바뀌는 오류 수정하기
- [x] 모두의 공간탭 줄넘김 이후 질문 짤리는거 수정하기
- [x] 카드뷰/리스트뷰 바꾸는 버튼 수정하기
- [x] 스플래쉬 로띠 적용하기

### 🔴 ETC
기타 사항을 적어주세요.
예상 개발 기간: 6시간
