### ISSUE TITLE
[#99]feedback: 피드백 2차

### ISSUE THREAD

**Issue by akrudal** [telling-me/tellingme-iOS#99]
### ✔ Todo
- [x] 다크모드 막기
- [x] 최신순>관련순>공감순
- [x] 설정 -> 이용약관 개인정보처리방침 파일로 바꾸기
- [x] 푸시 알림 괜찮아요 오류
- [x] 출생년도 플레이스 홀더 두기

### 🔴 ETC
기타 사항을 적어주세요.
예상 개발 기간:
